✨ OwnedRoles
Vectorized/solady pull request #50
Opened 2022-08-12 18:23 UTC by Vectorized

## Motivation

Right now, many code bases mix `Ownable` + `AccessControl`.

However, this requires an extra `SSTORE` on initialization just to give the contract owner the default admin role to grant/revoke roles. This can add a bothersome overhead for clones.

Usually, since the owner will be the only default admin role, the extra `SSTORE` is redundant from a logical point of view.

## Description

This PR combines `Ownable` + `AccessControl` in a minimalist way.

- Roles are represented / set / retrieved as 256 bit words, where each bit represent a single role. This allows us to get and set roles efficiently. Also, it is extremely unlikely that a project will need more than 255 roles.

- Compatible with both regular and upgradeable contracts.

- For simplicity, the owner can get and set all roles. If you don't want the owner to get and set certain roles, then simply set the owner to the zero address, and grant the owner an custom admin role instead. Then use the `onlyRoles` modifier on your own custom function to allow the custom admin role to manage only certain roles.

- `OwnerUpdated(address indexed newOwner)` only has one argument.

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [ ] Ran `forge snapshot`?
- [ ] Ran `npm run lint`?
- [ ] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

2022-08-15 14:47 UTC, Jorropo commented on src/auth/OwnableRoles.sol
> +    uint256 private constant _OWNER_SLOT_NEG = 0x18207379;
Nit picking but NOT and NEG means two different things.

NOT is a one's complement negation (flip all the bits).
NEG is a two's complement negation (do NOT(x) + 1).

I would call this variable `_OWNER_SLOT_NEG`.

2022-08-15 15:27 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +    uint256 private constant _OWNER_SLOT_NEG = 0x18207379;
Ok. Sounds good.

2022-08-16 00:33 UTC, Saw-mon-and-Natalie requested changes
@Vectorized , left some comments. Hope it will help 😊.

2022-08-16 00:33 UTC, Saw-mon-and-Natalie commented on src/auth/OwnableRoles.sol
> +    uint256 private constant _OWNER_SLOT_NOT = 0x18207379;
If we had `_OWNER_SLOT_NOT = 0x18207379 << 8 * 28 = 0x1820737900000000000000000000000000000000000000000000000000000000` instead of left-shifting `user` addresses to calculate their `role` storage slot we could have :

```solidity
mstore(0x00, or(user, _OWNER_SLOT_NOT))
let roleSlot := keccak256(0x00, 0x20)
```

without the `newOwner := shr(96, shl(96, newOwner))` bit.

2022-08-16 02:07 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +            result := eq(sload(keccak256(0x00, 0x20)), roles)
Wow. Thanks, nice catch! I will change it to the code you suggested.

2022-08-16 02:10 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +    uint256 private constant _OWNER_SLOT_NOT = 0x18207379;
I'm quite paranoid about the compiler not cleaning up the upper bits of the addresses. 

Lemme try some test that brutalizes the upper bits of the addresses.

2022-08-16 02:11 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +pragma solidity >=0.8.0;
I'll change this to `^0.8.4` later.

2022-08-16 02:12 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +            if iszero(eq(caller(), sload(handoverSlot))) {
wow, nice trick!

2022-08-16 02:18 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +    uint256 private constant _OWNER_SLOT_NOT = 0x18207379;
From my personal tests, I observe that the compiler can optimize the shifts away if it detects that the addresses are from a clean source (e.g. `msg.sender`), or already clean.

2022-08-16 03:13 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +            newOwner := shr(96, shl(96, newOwner))
Oh, the choice to use `shr(96, shl(96, newOwner))` is to reduce the size of the bytecode.

2022-08-16 03:16 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +            if iszero(eq(caller(), sload(not(_OWNER_SLOT_NOT)))) {
Hmm... it seems like the compiler optimizes out the `iszero` for `iszero(eq(caller(), sload(not(_OWNER_SLOT_NOT))))`. 

So the `xor` also gives the same gas.

2022-08-16 03:17 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +            if iszero(eq(caller(), sload(not(_OWNER_SLOT_NOT)))) {
Hmm... it seems like the compiler optimizes out the `iszero` for `iszero(eq(caller(), sload(not(_OWNER_SLOT_NOT))))`. 

So the `xor` also gives the same gas.

2022-08-16 03:45 UTC, Vectorized commented
@Saw-mon-and-Natalie I've strengthed the tests with some brutalizers.

I am paranoid of the dirty bits in the upper 96 bits of address (e.g. when the addresses come from a packed variable), so I feel it is better to add in the opcodes to clean them. Hopefully, the compiler is smart about it and will clean up the extra opcodes if they are not needed.

I think the compiler will evaluate the `not(_OWNER_SLOT_NOT)`, even without IR. When I tried copy pasting a bytes32 value that is not possible to be simplified (e.g. `0x7ced9b4df95b269341d83b1e9e5c9e4c93ed7f9e329a01520ffaf50a10192ac4`), the gas costs are still the same. I'll just let it be `not(_OWNER_SLOT_NOT)`, such that depending on the optimizer runs, the compiler may choose to evaluate it for better runtime costs, or leave it as it is for smaller bytecode size.

2022-08-16 19:19 UTC, merged

2022-08-18 20:00 UTC, hrkrshnn commented on src/auth/OwnableRoles.sol
> +            sstore(roleSlot, newRoles)
The slot is `keccak((owner << 96) | 0x8b78c6d8))`. Nothing wrong with this by itself. However, if you reuse the same storage scheme in a different contract, the storage collision can become nasty.

A hypothetical example is making an identical copy of `OwnableRoles` and a contract that inherits both of them. The way the compiler handles them is to key off a unique number. The slot for the corresponding mapping would be computed in the following way
```
mstore(0, uniqueid)
mstore(0x20, address)
keccak(0, 0x40)
```
This makes it resilient against collisions by having same logic in parent contracts.

To implement this in OwnableRoles, you could do something like
```solidity
contract OwnableRole {
     uint private HASHINGSALT;
     function hash(address _address) returns  returns (bytes32 ret) {
         assembly {
             mstore(0, HASHINGSALT.slot)
             mstore(0x20, _address)
             ret := keccak(0, 0x40)
         }
     }
}
```

The reason this works is that the storage slot for variable `HASHINGSALT` will always be unique. @Vectorized

2022-08-18 20:03 UTC, hrkrshnn commented on src/auth/OwnableRoles.sol
> +            sstore(roleSlot, newRoles)
Also, is it really worth it to do this way? What inefficiencies are you finding in a high level mapping? Perhaps it's easier to fix this in solc if you have specific concerns.

2022-08-18 21:29 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +            user := shl(96, user)
Hmm, but somehow if I don’t do this, the tests which brutalize the upper 96 buts will fail.

2022-08-18 21:33 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +            sstore(roleSlot, newRoles)
Ah, this idea of using a self provided “hash” for a slot is taken from EIP-2535. 

OwnableRoles is strictly intended to be used on its own too.

2022-08-18 21:35 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +            sstore(roleSlot, newRoles)
Ya, it’s for saving the few gas 😂 .

2022-08-18 21:41 UTC, Vectorized commented on src/auth/OwnableRoles.sol
> +            user := shl(96, user)
I’ve added a brutalized test for testInitializeOwnerDirect. If the cleaning in `_initializeOwner` is commented out, then the test will fail.