✨ Add UUPS Upgradeable
Vectorized/solady pull request #637
Opened 2023-10-08 16:00 UTC by atarapra

## Description

Add UUPS Pattern for smart contract upgrade. 
 
## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [ ] Ran `forge fmt`?
- [ ] Ran `forge snapshot`?
- [x] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

2023-10-08 20:02 UTC, Vectorized requested changes
Great work!

2023-10-08 20:02 UTC, Vectorized commented on src/utils/UUPSUpgradeable.sol
> +            }
```suggestion
            mstore(0x01, 0x52d1902d) // bytes4(keccak256("proxiableUUID()"))

            if iszero(
                eq(
                    mload(staticcall(gas(), newImplementation, 0x1d, 0x04, 0x01, 0x20)),
                    ERC1967_IMPLEMENTATION_SLOT
                )
            ) {
                mstore(0x00, 0x55299b49) // `UpgradeFailed()`.
                revert(0x1c, 0x04)
            }
```

2023-10-08 20:02 UTC, Vectorized commented on src/utils/UUPSUpgradeable.sol
> +
```suggestion
    bytes32 internal constant _ERC1967_IMPLEMENTATION_SLOT =
        0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc;

```

2023-10-08 20:02 UTC, Vectorized commented on src/utils/UUPSUpgradeable.sol
> +    function _upgradeTo(address newImplementation) internal virtual {
Change to public virtual. 

See: https://goerli.etherscan.io/address/0xf9dc117165100cdeae813e49e20d0d5a055e9e86#writeContract

2023-10-08 20:05 UTC, Vectorized commented
Should we emit the event for upgrade? Not compulsory though. 

https://eips.ethereum.org/EIPS/eip-1967#logic-contract-address

Reason for not emitting: save gas.

Reason for emitting: Most 4337 wallets will be on L2, where gas is cheap. Emitting can help making tracking upgrades easier.

2023-10-09 08:33 UTC, atarapra commented
Thinking more about upgraded event, it seems that it's not obligatory according to the (EIP). If someone desires to include the upgrade event, they have the option to override the function. You are right, Layer 2 gas costs are indeed economical in terms of gas prices, Solady continues to be well-regarded for its gas optimization capabilities, regardless of whether it's on Layer 1 or Layer 2. If we can save 1 gas then still I will go for it.

What are your thoughts on this?

2023-10-09 09:28 UTC, atarapra commented
Update: Etherscan automatically tracks contract upgrades without emitting a separate upgrade event. Additionally, it provides visibility into the previous implementation of the contract. So with help of etherscan users can track easily one previous implementation.

![image](https://github.com/Vectorized/solady/assets/66815072/ce2eada7-1b12-4dde-8c88-3ac67351d3bd)

2023-10-10 14:02 UTC, Vectorized reviewed
I think let's add the event.

The ERC1967Factory does emit a event, although not on the actual proxy itself.

Also, let's clear the upper 96 bits of the address.

2023-10-10 18:51 UTC, Vectorized approved these changes

2023-10-10 19:03 UTC, Vectorized commented
Optimizing for smaller bytecode size since upgrades are not intended to be often on L1s (e.g. in Defi singleton contracts), and are cheap on L2s (e.g. in 4337 wallets).

2023-10-10 23:46 UTC, merged